name: utils
'on':
  push: null
  schedule:
    - cron: 59 3 2-31/2 * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: 'npm:install'
        run: npm install
        env:
          CI: true
      - name: lint
        run: npm run lint --if-present
      - name: clone
        run: npm run dependencies:chromedriver
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
