name: utils
'on':
  push: null
  schedule:
    - cron: 5 0 1-31/2 * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
        env:
          CI: true
      - name: Lint
        run: npm run lint --if-present
      - name: Build
        run: npm run build --if-present
